server:
  port: 8088
  servlet:
    #应用路径，配置应用路径，可方便进行反向代理
    context-path: /
#    context-path: /xuezhang

spring:
  # 环境 dev|uat|prod
  profiles:
    active: dev
  application:
    name: hello-spring-boot
  thymeleaf:
    cache: false # 开发时关闭缓存，不然无法看到实时页面
    mode: HTML # 用非严格的html
    encoding: UTF-8
    servlet:
      content-type: text/html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  ## QQ邮箱配置
  mail:
    host: smtp.medsci.cn #发送邮件服务器
    username: service@medsci.cn #发送邮件的邮箱地址
    password: Bom+bom.cn190809 #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 25 #端口号465或587
    from: service@medsci.cn # 发送邮件的地址，和上面username一致可以任意
    #properties.mail.smtp.starttls.enable: true
    #properties.mail.smtp.starttls.required: true
    #properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  cloud:
    sentinel:
      enabled: true
      transport:
        dashboard: 127.0.0.1:8079
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000
    block-when-exhausted: true
    jedis:
      pool:
        max-idle: 200
        min-idle: 20
        max-active: 2000
        max-wait: 1000


mybatis:
  type-aliases-package: com.medsci.hello.spring.boot.domain
  mapper-locations: classpath:mapper/*.xml

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  file:
    name: hello-spring-boot.log
    path: /logs
  pattern:
    level: DEBUG


#------------------------------Dataway配置-------------------------------------------------
HASOR_DATAQL_DATAWAY: false # 是否启用 Dataway 功能（必选：默认false）
HASOR_DATAQL_DATAWAY_ADMIN: 默认false # 是否开启 Dataway 后台管理界面（必选：默认false）
HASOR_DATAQL_DATAWAY_API_URL: /api/ # dataway  API工作路径（可选，默认：/api/）
HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/ # dataway-ui 的工作路径（可选，默认：/interface-ui/）
HASOR_DATAQL_FX_PAGE_DIALECT: mysql # SQL执行器方言设置（可选，建议设置）

jwt:
  header: Authorization
  secret: spring-boot-secret
  expiration: 43200 # 12h
  tokenHead: "Bearer "
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /doc.html
      - /user/auth/*
      - /pdf/*
      - /excel/*
      - /rsa/*

filePath:
  sourcePath: temp/sourcePath/
  uploadPath: temp/uploadPath/